apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mosquitto-app
spec:
  selector:
    matchLabels:
      app: mosquitto-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mosquitto-app
    spec:
      volumes:
      - name: dmtcp-shared
        emptyDir: {}
      containers:
      - name: mosquitto
        image: harbor.ukserp.ac.uk/mycedrive/mycedrive-mosquitto-example:pr-21
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        - containerPort: 1883
        env:
        - name: DMTCP_COORD_HOST
          value: 127.0.0.1
        - name: DMTCP_CHECKPOINT_DIR
          value: /dmtcp/checkpoints
        volumeMounts:
        - name: dmtcp-shared
          mountPath: /dmtcp
        lifecycle:
          #postStart:
            #exec:
              #command: [ "./migAgent $root_dir $layers" ]
        # End script to make sure the checkpoints are created
          preStop:
            exec:
              command: [ "./end_container" ]
      - name: agent
        image: harbor.ukserp.ac.uk/mycedrive/mycedrive-agent:pr-21
        imagePullPolicy: Always
        command: ["cd /root/ && ./main $root_dir $layers"]
#        command: ["sleep 10000"]
        ports:
        - containerPort: 7779
        volumeMounts:
        - name: dmtcp-shared
          mountPath: /share 

